# Use Node.js official image
FROM node:20

# Set working directory inside the container
WORKDIR /app

# Copy only package.json and package-lock.json first to leverage Docker caching
COPY package.json package-lock.json /app/

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . /app/

# Build the frontend package
RUN npm run build

# Start the application (optional; only for development)
CMD ["npm", "run", "start"]
