
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    volumes:
      - /Users/Workspace/Abnormal Security/secure-file-share/backend:/backend
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: >
      sh -c "npm run dev"
