services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    image: secure-file-share-backend
    volumes:
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    image: secure-file-share-frontend  # Name the image explicitly
    environment:
      - VITE_API_URL=https://localhost/api

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/static:/usr/share/nginx/static
      - ./backend/media:/usr/share/nginx/media
      - ./certificates:/etc/nginx/certificates
