
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    volumes:
      - /Users/Workspace/Abnormal Security/secure-file-share/backend:/backend
    command: >
      sh -c "python manage.py runserver_plus 0.0.0.0:8000 --verbosity 3 --cert-file ./certificates/devserver.crt --key-file ./certificates/fileshare.key"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: >
      sh -c "npm run dev"